### ISSUE TITLE
[Layout] 프로필 설정 뷰

### ISSUE THREAD

**Issue by eunseo5355** [team-nutee/NUTEE-Android#39]
- [x] 프로필 설정 뷰 Activity Layout 구현

- [x] 프로필 설정 뷰 Fragment Layout 제작 

- [x] 프로필 설정 뷰 -1 Fragment Layout 제작 

- [x] 프로필 설정 뷰 -2 Fragment Layout 제작 

- [x] 프로필 설정 뷰 -3 Fragment Layout 제작 

- [x] 프로필 설정 뷰 -4 Fragment Layout 제작 

- [x] 프로필 설정 뷰 -5 Fragment Layout 제작

**Comment by jinsu4755** [comment]
지금 현재 이슈의 카테고리가 layout을 그리는 부분이니 구현보다는 그리기나 Layout 제작 혹은 레이아웃 구현 이런식으로 조금더 정확하게 해주면 좋을것 같고
상단바는 엑티비티에서 구현할듯 하니 프로필 설정 뷰 Activity Layout 구현 이런식이 더 구체적인거 같아
