### ISSUE TITLE
[Layout]디테일 뷰: 사진 자세히 보기

### ISSUE THREAD

**Issue by 88yhtserof** [team-nutee/NUTEE-Android#40]
- [x] 세부요소 배치
- [x] ViewPager 배치
- [x] Indicator 배치

**Comment by jinsu4755** [comment]
조금더 구체적으로 쓰는게 좋을 것 같아
예를 들면

사진 자세히보기 화면 구현 -> Activity
- [ ] 세부요소 배치하기
- [ ] 뷰 페이저 배치
- [ ] 인디케이터 배치하기
이런 느낌? 다른 파트에서 이슈를 봤을때 좀더 구체적으로 정확하게 이게 보이는것만 배치한건지 기능도 완료가 된건지 알아볼 수 있도록 하면 될 것 같아
